apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
data:
  nginx.conf: |
    events {
    worker_connections 1024;  # Adjust the number of worker connections as needed
    }

    http {
    include /etc/nginx/conf.d/*.conf;

    server {
        listen 80;
        server_name example.com;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /stub_status {
            stub_status;
        }
    }
    }
