apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanger
spec:
  selector:
    matchLabels:
      app: alertmanger
  template:
    metadata:
      labels:
        app: alertmanger
    spec:
      containers:
      - name: alertmanger
        image: prom/alertmanager
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9093
        volumeMounts:
          - name: config-volume
            mountPath: /etc/alertmanager/
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config  # Reference the ConfigMap
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
spec:
  type: LoadBalancer
  selector:
    app: alertmanger
  ports:
  - port: 9093
    targetPort: 9093
