apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "/etc/prometheus/alert_rules.yml"

    scrape_configs:
      - job_name: 'nginx-exporter'
        static_configs:
          - targets:
              - nginx-service.default:9113  # Replace with your exporter pod IP and port
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager-service.default:9093 

    
  alert_rules.yml: |
    groups:
    - name: nginx.alert
      rules:
      - alert: NginxIsUnrechable
        expr: nginx_up == 0
        for: 1m
        labels:
          severity: high
        annotations:
          description: nginx is down for 1 minute
