apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine3.20-perl
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
    
        volumeMounts:
          - mountPath: /etc/nginx/
            name: nginx-conf

      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:1.3  # Use the latest version
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9113  # Default port for NGINX Exporter
        args:
          - -nginx.scrape-uri=http://127.0.0.1:80/stub_status  # NGINX metrics endpoint
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-configuration
            items:
              - key: nginx.conf
                path: nginx.conf              
              

        

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
    - name: metrics
      port: 9113
      targetPort: 9113  
      protocol: TCP


